CREATE TABLE `creative_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`adId` varchar(100) NOT NULL,
	`periodFrom` varchar(10) NOT NULL,
	`periodTo` varchar(10) NOT NULL,
	`adName` varchar(500),
	`campaignName` varchar(500),
	`adsetName` varchar(500),
	`format` varchar(50),
	`thumbnailUrl` text,
	`hook` varchar(500),
	`angle` varchar(500),
	`promise` varchar(500),
	`proof` varchar(500),
	`offer` varchar(500),
	`callToAction` varchar(255),
	`performanceInsight` text,
	`testHypothesis` text,
	`confidence` int NOT NULL DEFAULT 0,
	`metrics` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `creative_analyses_id` PRIMARY KEY(`id`)
);
