CREATE TABLE `creative_briefs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`sourceCreativeAnalysisId` int,
	`periodFrom` varchar(10) NOT NULL,
	`periodTo` varchar(10) NOT NULL,
	`title` varchar(255) NOT NULL,
	`objective` varchar(255) NOT NULL,
	`targetAudience` text,
	`hypothesis` text NOT NULL,
	`hook` text NOT NULL,
	`angle` text NOT NULL,
	`coreMessage` text NOT NULL,
	`visualDirection` text NOT NULL,
	`script` text NOT NULL,
	`primaryText` text NOT NULL,
	`headline` varchar(500) NOT NULL,
	`callToAction` varchar(255) NOT NULL,
	`format` varchar(100) NOT NULL,
	`variableToTest` text NOT NULL,
	`successMetric` varchar(255) NOT NULL,
	`status` enum('draft','approved','rejected','tested') NOT NULL DEFAULT 'draft',
	`priority` int NOT NULL DEFAULT 2,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `creative_briefs_id` PRIMARY KEY(`id`)
);
