import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, Check, Download, ImagePlus, Loader2, Sparkles, Trash2, WandSparkles, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { composeBeforeAfterStatic } from "@/lib/beforeAfterComposition";

type Client = { id: number; name: string };
type Pair = { id: number; label: string; beforeUrl: string; afterUrl: string; consentConfirmed: boolean };
type Brief = { id: number; title: string; hook: string; callToAction: string; status: "draft" | "approved" | "rejected" | "tested" };
type StaticCreative = { id: number; imageUrl: string; aspectRatio: string; status: "generated" | "approved" | "rejected" };
function isoDate(date: Date) { return date.toISOString().slice(0, 10); }
function initialRange() { const to = new Date(); const from = new Date(); from.setDate(to.getDate() - 29); return { from: isoDate(from), to: isoDate(to) }; }
function readFile(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Não foi possível ler a imagem.")); reader.readAsDataURL(file); }); }

export default function ManagerBeforeAfterStudio() {
  const [, navigate] = useLocation();
  const [token, setToken] = useState<string | null>(null);
  const [clientId, setClientId] = useState<number | null>(null);
  const [label, setLabel] = useState("");
  const [beforeFile, setBeforeFile] = useState<File | null>(null);
  const [afterFile, setAfterFile] = useState<File | null>(null);
  const [consent, setConsent] = useState(false);
  const [selectedPairId, setSelectedPairId] = useState<number | null>(null);
  const [briefId, setBriefId] = useState<number | null>(null);
  const [aspectRatio, setAspectRatio] = useState<"4:5" | "9:16">("4:5");
  const [range] = useState(initialRange);

  useEffect(() => { const saved = localStorage.getItem("manager_token"); if (!saved) { navigate("/manager/login"); return; } setToken(saved); }, [navigate]);
  const clientsQuery = trpc.managers.myClients.useQuery({ token: token! }, { enabled: !!token });
  const clients = (clientsQuery.data?.clients ?? []) as Client[];
  useEffect(() => { if (!clientId && clients.length) setClientId(clients[0].id); }, [clientId, clients]);
  const pairsQuery = trpc.managers.getBeforeAfterPairsAsManager.useQuery({ token: token!, clientId: clientId! }, { enabled: !!token && !!clientId });
  const pairs = (pairsQuery.data?.pairs ?? []) as Pair[];
  useEffect(() => { if (!selectedPairId && pairs.length) setSelectedPairId(pairs[0].id); if (selectedPairId && !pairs.some((pair) => pair.id === selectedPairId)) setSelectedPairId(pairs[0]?.id ?? null); }, [pairs, selectedPairId]);
  const briefsQuery = trpc.managers.getCreativeBriefsAsManager.useQuery({ token: token!, clientId: clientId!, from: range.from, to: range.to }, { enabled: !!token && !!clientId });
  const approvedBriefs = useMemo(() => ((briefsQuery.data?.briefs ?? []) as Brief[]).filter((brief) => brief.status === "approved"), [briefsQuery.data?.briefs]);
  useEffect(() => { if (!briefId && approvedBriefs.length) setBriefId(approvedBriefs[0].id); }, [approvedBriefs, briefId]);
  const selectedPair = pairs.find((pair) => pair.id === selectedPairId) ?? null;
  const selectedBrief = approvedBriefs.find((brief) => brief.id === briefId) ?? null;
  const creativesQuery = trpc.managers.getBeforeAfterCreativesAsManager.useQuery({ token: token!, clientId: clientId!, pairId: selectedPairId! }, { enabled: !!token && !!clientId && !!selectedPairId });
  const creatives = (creativesQuery.data?.creatives ?? []) as StaticCreative[];

  const uploadMutation = trpc.managers.uploadBeforeAfterPairAsManager.useMutation({ onSuccess: async () => { await pairsQuery.refetch(); setLabel(""); setBeforeFile(null); setAfterFile(null); setConsent(false); toast.success("Par de antes e depois salvo no banco do cliente."); }, onError: (error) => toast.error(error.message || "Não foi possível enviar as fotos.") });
  const deleteMutation = trpc.managers.deleteBeforeAfterPairAsManager.useMutation({ onSuccess: async () => { await pairsQuery.refetch(); toast.success("Par removido."); }, onError: (error) => toast.error(error.message || "Não foi possível remover o par.") });
  const composeMutation = trpc.managers.saveComposedBeforeAfterCreativeAsManager.useMutation({ onSuccess: async () => { await creativesQuery.refetch(); toast.success("Estático composto com as fotos originais. Revise antes de usar no tráfego."); }, onError: (error) => toast.error(error.message || "Não foi possível salvar o estático.") });
  const generateMutation = composeMutation;
  const statusMutation = trpc.managers.updateBeforeAfterCreativeStatusAsManager.useMutation({ onSuccess: async () => { await creativesQuery.refetch(); toast.success("Status atualizado."); }, onError: (error) => toast.error(error.message || "Não foi possível atualizar o estático.") });

  function onFileChange(setter: (file: File | null) => void) { return (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0] ?? null; if (!file) return setter(null); if (!file.type.match(/^image\/(jpeg|png|webp)$/)) { toast.error("Use JPG, PNG ou WEBP."); event.target.value = ""; return; } if (file.size > 12 * 1024 * 1024) { toast.error("Cada foto deve ter no máximo 12 MB."); event.target.value = ""; return; } setter(file); }; }
  async function upload() { if (!token || !clientId || !beforeFile || !afterFile || !label.trim()) { toast.error("Preencha o nome e selecione as duas fotos."); return; } if (!consent) { toast.error("Confirme a autorização de uso das fotos."); return; } try { const [beforeBase64, afterBase64] = await Promise.all([readFile(beforeFile), readFile(afterFile)]); uploadMutation.mutate({ token, clientId, label: label.trim(), beforeBase64, afterBase64, beforeMimeType: beforeFile.type as "image/jpeg" | "image/png" | "image/webp", afterMimeType: afterFile.type as "image/jpeg" | "image/png" | "image/webp", consentConfirmed: true }); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível ler as fotos."); } }
  async function generate() {
    if (!token || !clientId || !selectedPairId || !briefId || !selectedPair || !selectedBrief) return;
    try {
      const imageBase64 = await composeBeforeAfterStatic({ beforeUrl: selectedPair.beforeUrl, afterUrl: selectedPair.afterUrl, aspectRatio, title: selectedBrief.title, hook: selectedBrief.hook, callToAction: selectedBrief.callToAction });
      composeMutation.mutate({ token, clientId, pairId: selectedPairId, briefId, aspectRatio, imageBase64 });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Não foi possível compor o estático com as fotos originais.");
    }
  }
  function updateStatus(creative: StaticCreative, status: StaticCreative["status"]) { if (!token || !clientId) return; statusMutation.mutate({ token, clientId, creativeId: creative.id, status }); }
  async function downloadCreative(creative: StaticCreative) {
    try {
      const response = await fetch(creative.imageUrl);
      if (!response.ok) throw new Error("Não foi possível baixar o arquivo.");
      const blob = await response.blob();
      const fileUrl = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = fileUrl;
      link.download = `criativo-antes-depois-${creative.id}-${creative.aspectRatio.replace(":", "x")}.png`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(fileUrl);
      toast.success("PNG baixado.");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Não foi possível baixar o PNG.");
    }
  }

  return <div className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-20 flex items-center justify-between gap-4 px-4 md:px-7 py-4 border-b border-border bg-card/95 backdrop-blur"><div className="flex items-center gap-3 min-w-0"><button onClick={() => navigate("/manager/creative-agent")} className="w-9 h-9 rounded-lg flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-muted"><ArrowLeft className="w-4 h-4" /></button><div><div className="flex items-center gap-2"><ImagePlus className="w-4 h-4 text-pink-300" /><h1 className="font-semibold text-base">Antes e Depois</h1></div><p className="text-xs text-muted-foreground mt-0.5">Banco autorizado para estáticos de tráfego.</p></div></div></header>
    <main className="max-w-7xl mx-auto px-4 md:px-7 py-6 space-y-6"><section className="rounded-2xl p-5 md:p-6 border" style={{ background: "linear-gradient(120deg, rgba(236,72,153,0.16), rgba(14,165,233,0.12))", borderColor: "rgba(244,114,182,0.28)" }}><div className="flex gap-3"><Sparkles className="w-5 h-5 text-pink-300 shrink-0 mt-0.5" /><div><h2 className="text-xl font-semibold">Crie estáticos com resultados reais e autorizados.</h2><p className="text-sm text-muted-foreground mt-2 leading-relaxed">Envie um par de fotos, escolha um brief aprovado e gere uma base visual que preserve o resultado verdadeiro. O sistema não adiciona texto nem promete resultados.</p></div></div></section>
      <section className="rounded-xl border border-border bg-card p-4 md:p-5"><div className="grid lg:grid-cols-[minmax(200px,0.8fr)_1fr_1fr] gap-4"><label className="block"><span className="text-xs font-medium">Cliente</span><select value={clientId ?? ""} onChange={(event) => { setClientId(Number(event.target.value)); setSelectedPairId(null); setBriefId(null); }} className="mt-1.5 w-full h-10 px-3 rounded-lg text-sm bg-background border border-border outline-none focus:border-pink-400/60"><option value="" disabled>Selecione</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="block"><span className="text-xs font-medium">Identificação do caso</span><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Ex.: Transplante capilar, 8 meses" className="mt-1.5 w-full h-10 px-3 rounded-lg text-sm bg-background border border-border outline-none focus:border-pink-400/60" /></label><div className="flex items-end"><button onClick={upload} disabled={uploadMutation.isPending || !clientId} className="h-10 w-full rounded-lg text-sm font-semibold text-white disabled:opacity-55 flex items-center justify-center gap-2" style={{ background: "#db2777" }}>{uploadMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <ImagePlus className="w-4 h-4" />}{uploadMutation.isPending ? "Enviando..." : "Salvar par"}</button></div></div><div className="grid sm:grid-cols-2 gap-4 mt-4"><label className="rounded-xl p-4 border border-dashed border-border hover:border-pink-400/50 cursor-pointer"><span className="block text-xs font-semibold">Foto ANTES</span><span className="block text-xs text-muted-foreground mt-1">JPG, PNG ou WEBP até 12 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={onFileChange(setBeforeFile)} className="hidden" /><span className="block mt-3 text-xs text-pink-300 truncate">{beforeFile?.name ?? "Selecionar foto"}</span></label><label className="rounded-xl p-4 border border-dashed border-border hover:border-pink-400/50 cursor-pointer"><span className="block text-xs font-semibold">Foto DEPOIS</span><span className="block text-xs text-muted-foreground mt-1">JPG, PNG ou WEBP até 12 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={onFileChange(setAfterFile)} className="hidden" /><span className="block mt-3 text-xs text-pink-300 truncate">{afterFile?.name ?? "Selecionar foto"}</span></label></div><label className="mt-4 flex items-start gap-2 text-xs text-muted-foreground cursor-pointer"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-0.5 accent-pink-500" />Confirmo que tenho autorização para usar estas imagens no banco interno e em criativos do cliente.</label></section>
      <section className="rounded-xl border border-border bg-card overflow-hidden"><div className="p-4 md:p-5 border-b border-border"><h2 className="font-semibold text-sm">Banco de casos</h2><p className="text-xs text-muted-foreground mt-1">Escolha um par para gerar um estático. Remover um par também remove os estáticos derivados dele.</p></div>{pairsQuery.isLoading ? <div className="py-12 flex justify-center"><Loader2 className="w-6 h-6 animate-spin text-pink-300" /></div> : pairs.length === 0 ? <div className="py-12 text-center text-sm text-muted-foreground">Nenhum par salvo para este cliente.</div> : <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 p-4 md:p-5">{pairs.map((pair) => <article key={pair.id} className={`rounded-xl border overflow-hidden ${selectedPairId === pair.id ? "border-pink-400/60" : "border-border"}`}><button onClick={() => setSelectedPairId(pair.id)} className="w-full text-left"><div className="grid grid-cols-2 bg-muted"><img src={pair.beforeUrl} alt={`${pair.label} antes`} className="aspect-square w-full object-cover" /><img src={pair.afterUrl} alt={`${pair.label} depois`} className="aspect-square w-full object-cover" /></div><div className="p-3"><p className="text-xs font-semibold truncate">{pair.label}</p><p className="text-[11px] text-emerald-300 mt-1">Autorização confirmada</p></div></button><div className="px-3 pb-3"><button onClick={() => { if (window.confirm("Remover este par e todos os estáticos derivados dele?")) deleteMutation.mutate({ token: token!, clientId: clientId!, pairId: pair.id }); }} disabled={deleteMutation.isPending} className="text-[11px] text-rose-300 hover:text-rose-200 flex items-center gap-1"><Trash2 className="w-3 h-3" />Remover</button></div></article>)}</div>}</section>
      <section className="rounded-xl border border-border bg-card p-4 md:p-5"><div className="grid md:grid-cols-3 gap-4"><label className="block"><span className="text-xs font-medium">Par selecionado</span><select value={selectedPairId ?? ""} onChange={(event) => setSelectedPairId(Number(event.target.value))} className="mt-1.5 w-full h-10 px-3 rounded-lg text-sm bg-background border border-border outline-none focus:border-pink-400/60"><option value="" disabled>Selecione o caso</option>{pairs.map((pair) => <option key={pair.id} value={pair.id}>{pair.label}</option>)}</select></label><label className="block"><span className="text-xs font-medium">Brief aprovado</span><select value={briefId ?? ""} onChange={(event) => setBriefId(Number(event.target.value))} className="mt-1.5 w-full h-10 px-3 rounded-lg text-sm bg-background border border-border outline-none focus:border-pink-400/60" disabled={!approvedBriefs.length}><option value="" disabled>{approvedBriefs.length ? "Selecione" : "Nenhum brief aprovado"}</option>{approvedBriefs.map((brief) => <option key={brief.id} value={brief.id}>{brief.title}</option>)}</select></label><div><span className="text-xs font-medium">Formato</span><div className="mt-1.5 flex gap-2"><button onClick={() => setAspectRatio("4:5")} className={`h-10 px-3 rounded-lg text-xs border ${aspectRatio === "4:5" ? "border-pink-400/60 text-pink-200 bg-pink-500/10" : "border-border text-muted-foreground"}`}>Feed 4:5</button><button onClick={() => setAspectRatio("9:16")} className={`h-10 px-3 rounded-lg text-xs border ${aspectRatio === "9:16" ? "border-pink-400/60 text-pink-200 bg-pink-500/10" : "border-border text-muted-foreground"}`}>Story 9:16</button></div></div></div><button onClick={generate} disabled={!selectedPair || !briefId || generateMutation.isPending} className="mt-4 h-10 px-4 rounded-lg text-sm font-semibold text-white disabled:opacity-55 flex items-center justify-center gap-2" style={{ background: "#db2777" }}>{generateMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <WandSparkles className="w-4 h-4" />}{generateMutation.isPending ? "Gerando estático..." : "Gerar estático para tráfego"}</button></section>
      <section className="rounded-xl border border-border bg-card overflow-hidden"><div className="p-4 md:p-5 border-b border-border"><h2 className="font-semibold text-sm">Estáticos gerados</h2><p className="text-xs text-muted-foreground mt-1">Aprove apenas as peças que preservarem corretamente o resultado real e estiverem de acordo com o brief.</p></div>{creativesQuery.isLoading ? <div className="py-12 flex justify-center"><Loader2 className="w-6 h-6 animate-spin text-pink-300" /></div> : !selectedPair ? <div className="py-12 text-center text-sm text-muted-foreground">Selecione um caso para visualizar os estáticos.</div> : creatives.length === 0 ? <div className="py-12 text-center text-sm text-muted-foreground">Ainda não há estáticos gerados para este caso.</div> : <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 p-4 md:p-5">{creatives.map((creative) => <article key={creative.id} className="rounded-xl overflow-hidden border border-border bg-background/40"><img src={creative.imageUrl} alt="Estático gerado a partir de antes e depois" className="w-full aspect-[4/5] object-cover bg-muted" /><div className="p-3"><p className="text-[11px] font-semibold text-pink-200">{creative.status === "approved" ? "Aprovado" : "Para revisão"} · {creative.aspectRatio}</p>{creative.status === "approved" ? <button onClick={() => downloadCreative(creative)} className="mt-3 w-full h-8 rounded-lg text-[11px] font-semibold border border-sky-400/30 text-sky-300 hover:bg-sky-500/10 flex items-center justify-center gap-1"><Download className="w-3 h-3" />Baixar PNG</button> : <div className="grid grid-cols-2 gap-2 mt-3"><button onClick={() => updateStatus(creative, "approved")} disabled={statusMutation.isPending} className="h-8 rounded-lg text-[11px] font-semibold border border-emerald-400/30 text-emerald-300 hover:bg-emerald-500/10 flex items-center justify-center gap-1"><Check className="w-3 h-3" />Aprovar</button><button onClick={() => updateStatus(creative, "rejected")} disabled={statusMutation.isPending} className="h-8 rounded-lg text-[11px] font-semibold border border-rose-400/30 text-rose-300 hover:bg-rose-500/10 flex items-center justify-center gap-1"><X className="w-3 h-3" />Descartar</button></div>}</div></article>)}</div>}</section>
    </main></div>;
}
