import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, Check, Image as ImageIcon, Loader2, Sparkles, WandSparkles, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type Client = { id: number; name: string };
type Brief = { id: number; title: string; status: "draft" | "approved" | "rejected" | "tested"; visualDirection: string; format: string };
type Asset = { id: number; imageUrl: string; aspectRatio: string; status: "generated" | "approved" | "rejected"; createdAt: Date | string };
function isoDate(date: Date) { return date.toISOString().slice(0, 10); }
function initialRange() { const to = new Date(); const from = new Date(); from.setDate(to.getDate() - 29); return { from: isoDate(from), to: isoDate(to) }; }
function statusText(status: Asset["status"]) { return status === "approved" ? "Aprovado" : status === "rejected" ? "Descartado" : "Para revisão"; }

export default function ManagerCreativeVisuals() {
  const [, navigate] = useLocation();
  const [token, setToken] = useState<string | null>(null);
  const [clientId, setClientId] = useState<number | null>(null);
  const [briefId, setBriefId] = useState<number | null>(null);
  const [aspectRatio, setAspectRatio] = useState<"4:5" | "9:16">("4:5");
  const [range] = useState(initialRange);

  useEffect(() => { const saved = localStorage.getItem("manager_token"); if (!saved) { navigate("/manager/login"); return; } setToken(saved); }, [navigate]);
  const clientsQuery = trpc.managers.myClients.useQuery({ token: token! }, { enabled: !!token });
  const clients = (clientsQuery.data?.clients ?? []) as Client[];
  useEffect(() => { if (!clientId && clients.length) setClientId(clients[0].id); }, [clientId, clients]);
  const briefsQuery = trpc.managers.getCreativeBriefsAsManager.useQuery({ token: token!, clientId: clientId!, from: range.from, to: range.to }, { enabled: !!token && !!clientId });
  const approvedBriefs = useMemo(() => ((briefsQuery.data?.briefs ?? []) as Brief[]).filter((brief) => brief.status === "approved"), [briefsQuery.data?.briefs]);
  useEffect(() => { if (!briefId && approvedBriefs.length) setBriefId(approvedBriefs[0].id); if (briefId && !approvedBriefs.some((brief) => brief.id === briefId)) setBriefId(approvedBriefs[0]?.id ?? null); }, [approvedBriefs, briefId]);
  const selectedBrief = approvedBriefs.find((brief) => brief.id === briefId) ?? null;
  const assetsQuery = trpc.managers.getCreativeAssetsAsManager.useQuery({ token: token!, clientId: clientId!, briefId: briefId! }, { enabled: !!token && !!clientId && !!briefId });
  const generateMutation = trpc.managers.generateCreativeAssetAsManager.useMutation({ onSuccess: async () => { await assetsQuery.refetch(); toast.success("Visual criado. Revise antes de usar em campanha."); }, onError: (error) => toast.error(error.message || "Não foi possível gerar o visual.") });
  const statusMutation = trpc.managers.updateCreativeAssetStatusAsManager.useMutation({ onSuccess: async () => { await assetsQuery.refetch(); toast.success("Status do visual atualizado."); }, onError: (error) => toast.error(error.message || "Não foi possível atualizar o visual.") });
  const assets = (assetsQuery.data?.assets ?? []) as Asset[];
  function generate() { if (!token || !clientId || !briefId) return; generateMutation.mutate({ token, clientId, briefId, aspectRatio }); }
  function setStatus(asset: Asset, status: Asset["status"]) { if (!token || !clientId) return; statusMutation.mutate({ token, clientId, assetId: asset.id, status }); }

  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-20 flex items-center justify-between gap-4 px-4 md:px-7 py-4 border-b border-border bg-card/95 backdrop-blur"><div className="flex items-center gap-3 min-w-0"><button onClick={() => navigate("/manager/creative-agent")} className="w-9 h-9 rounded-lg flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-muted" title="Voltar para Creative Agent"><ArrowLeft className="w-4 h-4" /></button><div><div className="flex items-center gap-2"><WandSparkles className="w-4 h-4 text-pink-300" /><h1 className="font-semibold text-base">Criativos Visuais</h1></div><p className="text-xs text-muted-foreground mt-0.5">Gere bases visuais a partir de briefs aprovados.</p></div></div></header>
    <main className="max-w-6xl mx-auto px-4 md:px-7 py-6 space-y-6">
      <section className="rounded-2xl p-5 md:p-6 border" style={{ background: "linear-gradient(120deg, rgba(236,72,153,0.16), rgba(124,58,237,0.13))", borderColor: "rgba(244,114,182,0.28)" }}><div className="flex flex-col lg:flex-row gap-5 lg:items-end lg:justify-between"><div className="max-w-2xl"><span className="inline-flex items-center gap-1.5 text-xs font-semibold rounded-full px-2.5 py-1" style={{ background: "rgba(244,114,182,0.15)", color: "#fbcfe8" }}><Sparkles className="w-3 h-3" /> Produção assistida</span><h2 className="text-xl md:text-2xl font-semibold mt-3">Transforme um brief aprovado em um visual de campanha.</h2><p className="text-sm text-muted-foreground mt-2 leading-relaxed">A imagem gerada é uma base visual. O texto, CTA e informações obrigatórias continuam no brief para revisão da equipe antes de qualquer publicação.</p></div><button onClick={generate} disabled={!selectedBrief || generateMutation.isPending} className="h-10 px-4 rounded-lg text-sm font-semibold flex items-center justify-center gap-2 text-white disabled:opacity-55" style={{ background: "#db2777" }}>{generateMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <WandSparkles className="w-4 h-4" />}{generateMutation.isPending ? "Gerando visual..." : "Gerar visual"}</button></div></section>
      <section className="rounded-xl border border-border bg-card p-4 md:p-5 grid md:grid-cols-3 gap-4"><label className="block"><span className="text-xs font-medium">Cliente</span><select value={clientId ?? ""} onChange={(event) => { setClientId(Number(event.target.value)); setBriefId(null); }} className="mt-1.5 w-full h-10 px-3 rounded-lg text-sm bg-background border border-border outline-none focus:border-pink-400/60"><option value="" disabled>Selecione</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="block"><span className="text-xs font-medium">Brief aprovado</span><select value={briefId ?? ""} onChange={(event) => setBriefId(Number(event.target.value))} disabled={!approvedBriefs.length} className="mt-1.5 w-full h-10 px-3 rounded-lg text-sm bg-background border border-border outline-none focus:border-pink-400/60 disabled:opacity-55"><option value="" disabled>{approvedBriefs.length ? "Selecione o brief" : "Nenhum brief aprovado"}</option>{approvedBriefs.map((brief) => <option key={brief.id} value={brief.id}>{brief.title}</option>)}</select></label><label className="block"><span className="text-xs font-medium">Formato visual</span><select value={aspectRatio} onChange={(event) => setAspectRatio(event.target.value as "4:5" | "9:16")} className="mt-1.5 w-full h-10 px-3 rounded-lg text-sm bg-background border border-border outline-none focus:border-pink-400/60"><option value="4:5">Feed 4:5</option><option value="9:16">Story/Reel 9:16</option></select></label></section>
      {selectedBrief && <section className="rounded-xl border border-border bg-card p-4 md:p-5"><div className="flex gap-3"><ImageIcon className="w-5 h-5 text-pink-300 shrink-0 mt-0.5" /><div><h2 className="font-semibold text-sm">Direção do brief selecionado</h2><p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">{selectedBrief.visualDirection}</p><p className="text-xs mt-3"><span className="text-muted-foreground">Formato do brief:</span> {selectedBrief.format}</p></div></div></section>}
      <section className="rounded-xl border border-border bg-card overflow-hidden"><div className="p-4 md:p-5 border-b border-border"><h2 className="font-semibold text-sm">Visuais gerados para este brief</h2><p className="text-xs text-muted-foreground mt-1">Revise o resultado e aprove apenas o que estiver coerente com a marca, o briefing e as regras de publicidade do cliente.</p></div>{assetsQuery.isLoading ? <div className="py-16 flex justify-center"><Loader2 className="w-6 h-6 animate-spin text-pink-300" /></div> : !briefId ? <div className="py-16 text-center text-sm text-muted-foreground">Escolha um brief aprovado para visualizar ou gerar os criativos.</div> : assets.length === 0 ? <div className="py-16 px-5 text-center"><ImageIcon className="w-8 h-8 mx-auto text-muted-foreground/60" /><p className="text-sm text-muted-foreground mt-3">Ainda não há visual gerado para este brief.</p></div> : <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 p-4 md:p-5">{assets.map((asset) => <article key={asset.id} className="rounded-xl overflow-hidden border border-border bg-background/40"><img src={asset.imageUrl} alt="Criativo visual gerado" className="w-full aspect-[4/5] object-cover bg-muted" /><div className="p-3"><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-semibold text-pink-200">{statusText(asset.status)}</span><span className="text-[11px] text-muted-foreground">{asset.aspectRatio}</span></div><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={() => setStatus(asset, "approved")} disabled={statusMutation.isPending} className="h-8 rounded-lg text-[11px] font-semibold border border-emerald-400/30 text-emerald-300 hover:bg-emerald-500/10 disabled:opacity-50 flex items-center justify-center gap-1"><Check className="w-3 h-3" />Aprovar</button><button onClick={() => setStatus(asset, "rejected")} disabled={statusMutation.isPending} className="h-8 rounded-lg text-[11px] font-semibold border border-rose-400/30 text-rose-300 hover:bg-rose-500/10 disabled:opacity-50 flex items-center justify-center gap-1"><X className="w-3 h-3" />Descartar</button></div></div></article>)}</div>}</section>
    </main>
  </div>;
}
